// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otockznhpdhdpmnhxylb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90b2Nrem5ocGRoZHBtbmh4eWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjEyODcsImV4cCI6MjA3MTg5NzI4N30._RNhNrrc6tso4L7BkZZYlU9pXDte7NUAfO6oGENNRHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});